<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Note [

  <!---============== Tùy thành phần ==================-->

  <!ELEMENT Note ((contain)+)>
  <!ELEMENT contain (block, type)>
  <!ELEMENT block (#PCDATA)>
  <!ELEMENT type (#PCDATA)>

]>
<!--============ Config data ==============-->
<Note>
  <!--============ Print ==============-->
  <contain>
    <block>in</block>
    <type>print</type>
  </contain>
  <contain>
    <block>out</block>
    <type>print</type>
  </contain>
  <contain>
    <block>in_ra_màn_hình</block>
    <type>print</type>
  </contain>
  <!--============ Variable ==============-->
  <contain>
    <block>var</block>
    <type>variable</type>
  </contain>
</Note>